- name: Show run and backup config to TFTP
  hosts: switches
  gather_facts: yes
  tasks:
    - name: Backup config to TFTP
      cisco.ios.ios_command:
        commands:
          - "sh run | redirect tftp://10.20.30.50/{{ inventory_hostname }},{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}-{{ ansible_date_time.second }}.txt"
      register: running_config

    - name: Show return
      debug:
        var: running_config.stdout_lines
