- name: Backup switch configuration to TFTP
  hosts: switches
  gather_facts: no
  tasks:
    - name: Get current date and time from Ansible
      set_fact:
        ansible_date: "{{ '%Y-%m-%d_%H-%M-%S' | strftime(now().timestamp()) }}"

    - name: Ensure /semaphore/data directory exists
      file:
        path: /semaphore/data
        state: directory
        mode: '0755'

    - name: Get running configuration from switch
      cisco.ios.ios_command:
        commands:
          - show run
      register: running_config

    - name: Save running config to a local file
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "/semaphore/data/{{ inventory_hostname }}_{{ ansible_date }}.txt"

    - name: Debug local file
      stat:
        path: "/semaphore/data/{{ inventory_hostname }}_{{ ansible_date }}.txt"
      register: file_stat

    - name: Show local file info
      debug:
        var: file_stat

    - name: Upload config file to TFTP server
      command: >
        curl -T /semaphore/data/{{ inventory_hostname }}_{{ ansible_date }}.txt
        tftp://10.20.30.50/{{ inventory_hostname }}_{{ ansible_date }}.txt
      args:
        creates: /semaphore/data/{{ inventory_hostname }}_{{ ansible_date }}.txt
      register: upload_result

    - name: Debug upload result
      debug:
        var: upload_result

    - name: Clean up local file
      file:
        path: "/semaphore/data/{{ inventory_hostname }}_{{ ansible_date }}.txt"
        state: absent
