- name: Show run and backup config to TFTP
  hosts: switches
  gather_facts: no
  tasks:
    - name: Backup config to TFTP
      cisco.ios.ios_command:
        commands:
          - "sh run | redirect tftp://10.20.30.50/{{ inventory_hostname }}.txt"
      register: running_config

    - name: Show return
      debug:
        var: running_config.stdout_lines
