---
- name: Universal Package Installer
  hosts: all
  become: yes
  tasks:
    - name: Install packages from variable
      package:
        name: "{{ packages_to_install }}"
        state: present
      register: install_result

    - name: Show installed packages
      debug:
        msg: "Installed packages: {{ packages_to_install }}"
