---
- name: Install Neofetch
  hosts: all
  become: yes
  tasks:
    - name: Run installation command
      command: "{{ install_command }}"
      register: result

    - name: Show output
      debug:
        msg: "{{ result.stdout }}"
