---
- name: Set hostname based on current IP
  hosts: switches
  gather_facts: no
  tasks:
    - name: Get current IP of VLAN 1
      ios_command:
        commands:
          - show ip interface brief | include Vlan1
      register: vlan_ip_output

    - name: Extract IP address from output
      set_fact:
        current_ip: "{{ vlan_ip_output.stdout_lines[0].split()[1] }}"

    - name: Calculate hostname from IP
      set_fact:
        hostname: "cisco-atea-{{ current_ip.split('.')[-1] }}"

    - name: Set hostname on the switch
      ios_config:
        lines:
          - "hostname {{ hostname }}"
