---
- name: Configure Cisco switch with dynamic hostname
  hosts: switches
  gather_facts: no
  tasks:
    - name: Get current IP of VLAN 1
      ios_command:
        commands:
          - show ip interface brief | include Vlan1
      register: vlan_ip_output

    - name: Debug VLAN IP output
      debug:
        var: vlan_ip_output

    - name: Extract IP address from output
      set_fact:
        current_ip: "{{ vlan_ip_output.stdout[0].split()[1] }}"
      when: vlan_ip_output.stdout | length > 0

    - name: Validate that current IP was extracted
      fail:
        msg: "Failed to extract IP address for VLAN 1."
      when: current_ip is not defined

    - name: Calculate hostname from IP
      set_fact:
        hostname: "cisco-atea-{{ current_ip.split('.')[-1] }}"

    - name: Set dynamic hostname on the switch
      ios_config:
        lines:
          - "hostname {{ hostname }}"

    - name: Set basic configuration
      ios_config:
        lines:
          - "version 17.12"
          - "service timestamps debug datetime msec"
          - "service timestamps log datetime msec"
          - "no aaa new-model"
          - "ip audit notify log"
          - "ip audit po max-events 100"
          - "ip domain name atea.site"
          - "ip cef"
          - "login on-success log"
          - "no ipv6 cef"
          - "vtp version 1"
          - "multilink bundle-name authenticated"
          - "memory free low-watermark processor 80589"
          - "spanning-tree mode rapid-pvst"
          - "spanning-tree extend system-id"

    - name: Configure username
      ios_config:
        lines:
          - 'username atea privilege 15 secret 9 $9$nE7EM.dgiOvxVk$4gUmb75xn42KEGO2q6zS6X.W/SDz0GqLIbhOLXkdSHs'

    - name: Configure VLAN
      ios_config:
        lines:
          - "vlan internal allocation policy ascending"

    - name: Configure interfaces
      ios_config:
        lines:
          - "interface Ethernet0/0"
          - "interface Ethernet0/1"
          - "interface Ethernet0/2"
          - "interface Ethernet0/3"
          - "interface Vlan1"
          - " ip address dhcp"

    - name: Configure IP forwarding and HTTP
      ios_config:
        lines:
          - "ip forward-protocol nd"
          - "ip http server"
          - "ip http secure-server"
          - "ip ssh bulk-mode 131072"

    - name: Configure logging and SNMP
      ios_config:
        lines:
          - "logging host 10.20.30.50"
          - "snmp-server community ro RO"
          - "snmp-server community public RO"

    - name: Configure line settings
      ios_config:
        lines:
          - "line con 0"
          - " logging synchronous"
          - "line aux 0"
          - "line vty 0 4"
          - " login local"
          - " transport input ssh"
