---
- hosts: proxmox
  tasks:
    - name: Execute command
      ansible.builtin.command:
        cmd: bash /mnt/pve/NFS/cloud-init/config/create_vm_arguments {{ core }} {{ memo }} {{ disc }} {{ ip }}
      register: result


    - name: Display output
      ansible.builtin.debug:
        var: result.stdout_lines
