---
- name: Factory reset switches
  hosts: switches
  gather_facts: no
  tasks:
    - name: Erase startup configuration
      ios_command:
        commands:
          - write erase
      wait_for: "Continue? [confirm]"
      timeout: 30

    - name: Send confirmation for erase
      ios_command:
        commands:
          - "\n"

    - name: Reload the switch
      ios_command:
        commands:
          - reload
      wait_for: "Save? [yes/no]"
      timeout: 30

    - name: Answer no for saving configuration
      ios_command:
        commands:
          - no

    - name: Confirm reload
      ios_command:
        commands:
          - "\n"
