---
- name: Factory reset switches
  hosts: switches
  gather_facts: no
  tasks:
    - name: Erase startup configuration
      ios_command:
        commands:
          - write erase

    - name: Reload the switch
      ios_command:
        commands:
          - reload
        prompts:
          - "Proceed with reload? [confirm]"
        answers:
          - "Proceed with reload? [confirm]": "\r"
