---
- name: Factory reset switches
  hosts: switches
  gather_facts: no
  tasks:
    - name: Erase startup configuration
      ios_command:
        commands:
          - write erase

    - name: Confirm erase operation
      ios_command:
        commands:
          - "\n"  # Wysłanie Enter, aby potwierdzić

    - name: Reload the switch
      ios_command:
        commands:
          - reload

    - name: Decline saving configuration
      ios_command:
        commands:
          - no  # Odpowiedź na pytanie o zapisanie konfiguracji

    - name: Confirm reload operation
      ios_command:
        commands:
          - "\n"  # Wysłanie Enter, aby potwierdzić
