---
- name: Factory reset switches
  hosts: switches
  gather_facts: no
  tasks:
    - name: Erase startup configuration
      ios_command:
        commands:
          - write erase
      register: erase_output

    - name: Debug erase output
      debug:
        var: erase_output

    - name: Reload the switch without confirmation prompts
      ios_command:
        commands:
          - reload
          - no
          - confirm
