---
- hosts: proxmox
  tasks:
    - name: Execute command
      ansible.builtin.command:
        cmd: bash /mnt/pve/MAIN_NFS/cloud-init/config/create_debian_arguments {{ core }} {{ memo }} {{ disc }} {{ ip | default('dhcp') }}
      register: result

    - name: Display output
      ansible.builtin.debug:
        var: result.stdout_lines
